modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
modId="braziliannight"
version="0.1.0"
displayName="Brazilian Night"
authors="withp aldeezy charles_"
description='''
Become Meguca
'''

[[dependencies.braziliannight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"